// BindingEntry.swift
// BridgeKit iOS engine — internal representation of a live provider binding.
//
// Port of io/github/malopezr7/bridgekit/core/BindingEntry.kt + Binding.kt
//
// DESIGN: Holds the adapter + isLive flag + per-binding stream job registry.
// INV-5 (H-7): registerStreamJob rechecks isLive after insert and cancels immediately
// if the binding was closed in the window between openStream's binding check and job registration.

import Foundation

// ---- CloseReason -----------------------------------------------------------

/// Reason a binding was closed.
///
/// Port: `sealed class CloseReason` (Kotlin) → `enum CloseReason` (Swift).
public enum CloseReason {
    /// Binding is being replaced. The router holds in-flight calls for a grace window.
    case replacing
    /// Binding is permanently closed. All pending calls fail immediately.
    case final_

    /// Grace window for Replacing close (ms). Mirror of Kotlin constant.
    public static let replacingGraceMs: Int64 = 1500
}

// ---- Binding protocol ------------------------------------------------------

/// Handle to a live provider binding returned from `BridgeKit.provide`.
///
/// Port: `interface Binding` (Kotlin).
public protocol Binding: AnyObject {
    var contractId: String { get }
    var scope: Scope { get }
    var isLive: Bool { get }

    /// Close this binding with the given reason. No-op if already closed.
    func close(reason: CloseReason)
}

public extension Binding {
    func close() { close(reason: .final_) }
}

// ---- InboundContractAdapter (protocol) ------------------------------------

/// Adapts a typed provider implementation to the engine's untyped wire surface.
///
/// Port: `interface InboundContractAdapter` (Kotlin) → protocol (Swift).
/// Implementations are generated by the CLI per contract.
public protocol InboundContractAdapter: AnyObject {
    /// Initial state values keyed by state member name.
    var stateInitials: [String: Any?] { get }

    /// Async member dispatch.
    func invoke(member: String, payload: [String: Any?]?) async throws -> Any?

    /// Sync member dispatch (in-memory reads only).
    func invokeSync(member: String, payload: [String: Any?]?) throws -> Any?

    /// Return an AsyncThrowingStream for the given stream member.
    func openStream(member: String, payload: [String: Any?]?) -> AsyncThrowingStream<Any?, Error>

    /// All provider state streams keyed by state member name.
    /// Returns AsyncStream<Any?> wrappers (Swift equivalent of Kotlin StateFlow<Any?>).
    func stateStreams() -> [String: AsyncStream<Any?>]
}

// ---- BindingEntry ----------------------------------------------------------

/// Internal live binding.
///
/// Port: `class BindingEntry` (Kotlin).
internal final class BindingEntry {

    let definition: AnyBridgeContractDefinition
    let scope: Scope
    let adapter: InboundContractAdapter
    let contractId: String

    // PORT NOTE: Kotlin used @Volatile var _isLive.
    // Swift: plain Bool guarded by the engine NSRecursiveLock (all reads/writes happen
    // inside the engine lock in Router paths).
    private var _isLive: Bool = true
    var isLive: Bool { _isLive }

    // H-7: stream job registry. Guarded by engine lock.
    // PORT NOTE: Kotlin used ConcurrentHashMap<String, Job>. Swift: plain Dictionary
    // guarded by the engine NSRecursiveLock.
    private var streamJobs: [String: Task<Void, Never>] = [:]

    // State stream observation tasks (collect provider → stateStore).
    private var stateObservationTasks: [Task<Void, Never>] = []

    internal init(
        definition: AnyBridgeContractDefinition,
        scope: Scope,
        adapter: InboundContractAdapter
    ) {
        self.definition = definition
        self.scope = scope
        self.adapter = adapter
        self.contractId = definition.id
    }

    // -------------------------------------------------------------------------
    // Lifecycle
    // -------------------------------------------------------------------------

    internal func close(reason: CloseReason) {
        guard _isLive else { return }
        _isLive = false
        cancelAllStreamJobs()
        cancelStateObservations()
    }

    // -------------------------------------------------------------------------
    // Stream job registry (INV-5 H-7)
    // -------------------------------------------------------------------------

    /// Register a stream job.
    /// INV-5 (H-7): recheck isLive after insert; cancel immediately if binding was
    /// closed between the caller's check and this registration.
    internal func registerStreamJob(_ streamId: String, job: Task<Void, Never>) {
        streamJobs[streamId] = job
        if !_isLive {
            streamJobs.removeValue(forKey: streamId)
            job.cancel()
        }
    }

    internal func cancelStreamJob(_ streamId: String) {
        streamJobs.removeValue(forKey: streamId)?.cancel()
    }

    internal func cancelAllStreamJobs() {
        for (_, job) in streamJobs { job.cancel() }
        streamJobs.removeAll()
    }

    // -------------------------------------------------------------------------
    // State observation tasks
    // -------------------------------------------------------------------------

    internal func addStateObservation(_ task: Task<Void, Never>) {
        stateObservationTasks.append(task)
    }

    internal func cancelStateObservations() {
        for task in stateObservationTasks { task.cancel() }
        stateObservationTasks.removeAll()
    }
}
