// ---------------------------------------------------------------------------
// emit/assemble.ts — pure file-layout for a generated <Name>Contract.kt.
//
// Takes the precomputed string fragments (types, interfaces, codecs, member
// impls, state entries) and lays them out into the final Kotlin source. No
// schema walking, no codec decisions — those live in kotlin.ts / codec.ts.
// This is the D9 "assembly tail" lifted out so each emit module stays < 500 LOC.
// ---------------------------------------------------------------------------

export interface EmitResult {
  fileName: string;
  content: string;
}

export interface ContractFileParts {
  fileName: string;
  id: string;
  hash: string;
  kotlinPackage: string;
  className: string;
  codegenVersion: string;
  /** Top-level type declarations (data classes, sealed classes, enums). */
  typeDecls: string[];
  /** Provider interface method signatures. */
  providerMethods: string[];
  /** Client interface method signatures. */
  clientMethods: string[];
  /** Codec functions (object/union encode+decode). */
  encodeDecodeFns: string[];
  /** `"member" to "hash"` pairs for the memberHashes map. */
  memberHashPairs: string[];
  /** inbound invoke() member branches (indented at 12 spaces, codec-call body). */
  inboundImpls: string[];
  /** inbound invoke_sync() member branches. */
  syncImpls: string[];
  /** inbound openStream() member branches. */
  streamImpls: string[];
  /** outbound client method overrides. */
  outboundImpls: string[];
  /** `"name" to <literal>,` initial state entries. */
  stateInitials: string[];
  /** stateFlows() mapOf entries (without trailing comma — joined here). */
  stateFlowEntries: string[];
  /** Whether to import kotlinx.coroutines.flow.map (B6 per-item stream codec). */
  streamNeedsFlowMap: boolean;
  /** Whether to import java.time.Instant (t.date() type). */
  needsInstantImport: boolean;
  /**
   * Whether to import com.bridgekit.runtime.BridgeKitDecodeException.
   * True when any method result, stream item, or state value resolves to a
   * scalar that hits boundaryDecode's throw path (date, binary, enum, int64),
   * OR when encodeDecodeFns is non-empty (object/union codec path also throws).
   */
  needsBridgeKitDecodeException: boolean;
}

/** Indent each line of a multi-line fragment by `pad` spaces. */
function indentBlock(fragment: string, pad: string): string {
  return fragment
    .split('\n')
    .map((l) => `${pad}${l}`)
    .join('\n');
}

export function assembleContractFile(parts: ContractFileParts): EmitResult {
  const {
    fileName,
    id,
    hash,
    kotlinPackage,
    className,
    codegenVersion,
    typeDecls,
    providerMethods,
    clientMethods,
    encodeDecodeFns,
    memberHashPairs,
    inboundImpls,
    syncImpls,
    streamImpls,
    outboundImpls,
    stateInitials,
    stateFlowEntries,
    streamNeedsFlowMap,
    needsInstantImport,
    needsBridgeKitDecodeException,
  } = parts;

  const lines: string[] = [];

  // Header
  lines.push(`// Generated by bridgekit ${codegenVersion}. DO NOT EDIT.`);
  lines.push(`// Contract: ${id}`);
  lines.push(`// Contract hash: ${hash}`);
  lines.push(``);
  lines.push(`package ${kotlinPackage}`);
  lines.push(``);
  lines.push(`import com.bridgekit.runtime.BridgeContractDefinition`);
  lines.push(`import com.bridgekit.runtime.BridgeValue`);
  // Generated decoders fail-fast on missing/wrong-typed required fields (W1-5).
  // Also needed when any scalar result hits boundaryDecode's throw path (CRITICAL-1).
  if (encodeDecodeFns.length > 0 || needsBridgeKitDecodeException) {
    lines.push(`import com.bridgekit.runtime.BridgeKitDecodeException`);
  }
  lines.push(`import com.bridgekit.runtime.InboundContractAdapter`);
  lines.push(`import com.bridgekit.runtime.OutboundCaller`);
  if (needsInstantImport) {
    lines.push(`import java.time.Instant`);
  }
  if (streamNeedsFlowMap) {
    lines.push(`import kotlinx.coroutines.flow.map`);
  }
  lines.push(``);

  // Type declarations (data classes, sealed interfaces, enums)
  if (typeDecls.length > 0) {
    lines.push('// ---- Types ----------------------------------------------------------------');
    lines.push('');
    for (const decl of typeDecls) {
      lines.push(decl);
      lines.push('');
    }
  }

  // Provider interface
  lines.push('// ---- Provider interface -------------------------------------------------------');
  lines.push('');
  lines.push(`/** Native-side implementation interface for contract '${id}'. */`);
  lines.push(`interface ${className} {`);
  lines.push(...providerMethods);
  lines.push(`}`);
  lines.push('');

  // Client interface
  lines.push('// ---- Client interface ---------------------------------------------------------');
  lines.push('');
  lines.push(`/** RN-side consumer interface for contract '${id}'. */`);
  lines.push(`interface ${className}Client {`);
  lines.push(...clientMethods);
  lines.push(`}`);
  lines.push('');

  // Encode/decode helpers
  if (encodeDecodeFns.length > 0) {
    lines.push(
      '// ---- Codecs -------------------------------------------------------------------',
    );
    lines.push('');
    lines.push(`private object ${className}Codecs {`);
    for (const fn of encodeDecodeFns) {
      lines.push(indentBlock(fn, '    '));
      lines.push('');
    }
    lines.push('}');
    lines.push('');
  }

  // Definition object
  lines.push('// ---- Contract definition ------------------------------------------------------');
  lines.push('');
  lines.push(
    `object ${className}Contract : BridgeContractDefinition<${className}, ${className}Client>(`,
  );
  lines.push(`    id = "${id}",`);
  lines.push(`    contractHash = "${hash}",`);
  lines.push(`    memberHashes = mapOf(`);
  for (let i = 0; i < memberHashPairs.length; i++) {
    const comma = i < memberHashPairs.length - 1 ? ',' : '';
    lines.push(`        ${memberHashPairs[i]}${comma}`);
  }
  lines.push(`    )`);
  lines.push(`) {`);
  lines.push('');

  // inbound adapter
  lines.push(`    override fun inbound(impl: ${className}): InboundContractAdapter =`);
  lines.push(`        object : InboundContractAdapter {`);
  lines.push(`            override val stateInitials: Map<String, Any?> = mapOf(`);
  lines.push(...stateInitials);
  lines.push(`            )`);
  lines.push('');
  lines.push(
    `            override suspend fun invoke(member: String, payload: Map<String, Any?>?): Any? =`,
  );
  lines.push(`                when (member) {`);
  for (const impl of inboundImpls) {
    lines.push(indentBlock(impl, '    '));
  }
  lines.push(
    `                    else -> throw IllegalArgumentException("Unknown member: $member")`,
  );
  lines.push(`                }`);
  lines.push('');
  lines.push(
    `            override fun invokeSync(member: String, payload: Map<String, Any?>?): Any? =`,
  );
  lines.push(`                invoke_sync(member, payload)`);
  lines.push('');
  lines.push(
    `            private fun invoke_sync(member: String, payload: Map<String, Any?>?): Any? =`,
  );
  lines.push(`                when (member) {`);
  for (const impl of syncImpls) {
    lines.push(indentBlock(impl, '    '));
  }
  lines.push(
    `                    else -> throw IllegalArgumentException("Unknown sync member: $member")`,
  );
  lines.push(`                }`);
  lines.push('');
  lines.push(
    `            override fun openStream(member: String, payload: Map<String, Any?>?): kotlinx.coroutines.flow.Flow<Any?> =`,
  );
  lines.push(`                when (member) {`);
  for (const impl of streamImpls) {
    lines.push(indentBlock(impl, '    '));
  }
  lines.push(
    `                    else -> throw IllegalArgumentException("Unknown stream: $member")`,
  );
  lines.push(`                }`);
  lines.push('');
  lines.push(
    `            override fun stateFlows(): Map<String, kotlinx.coroutines.flow.StateFlow<Any?>> =`,
  );
  lines.push(`                mapOf(`);
  for (let i = 0; i < stateFlowEntries.length; i++) {
    const comma = i < stateFlowEntries.length - 1 ? ',' : '';
    lines.push(`${stateFlowEntries[i]}${comma}`);
  }
  lines.push(`                )`);
  lines.push(`        }`);
  lines.push('');

  // outbound proxy
  lines.push(`    override fun outbound(caller: OutboundCaller): ${className}Client =`);
  lines.push(`        object : ${className}Client {`);
  for (const impl of outboundImpls) {
    lines.push(indentBlock(impl, '    '));
  }
  lines.push(`        }`);
  lines.push(`}`);

  return {
    fileName,
    content: `${lines.join('\n')}\n`,
  };
}
