// emit/swift.ts — Swift contract file generation from a ContractDescriptor.

import type { RawContractToken } from '../load.js';
import type { EmitResult } from './assemble.js';
import { SwiftCodecWalker, schemaNeedsCodec } from './swift-codec.js';
import {
  escapeSwiftIdentifier,
  SwiftTypeEmitter,
  swiftLiteralForSchema,
  swiftStringLiteral,
} from './swift-types.js';
import {
  type ArrayNode,
  contractIdToClassName,
  hashMember,
  type NullableNode,
  type ObjectNode,
  type OneOfNode,
  type OptionalNode,
  type RecordNode,
  type SchemaNode,
  type TupleNode,
  toPascalCase,
  type UnionNode,
} from './types.js';

export type { EmitResult };

// ---- per-method descriptor shapes ------------------------------------------

interface MethodDescRaw {
  kind: 'fire' | 'query' | 'querySync';
  params?: ObjectNode;
  result?: SchemaNode;
  timeoutMs?: number | null;
}

interface StreamDescRaw {
  kind: 'stream';
  value: SchemaNode;
  params?: ObjectNode;
}

interface StateDescRaw {
  kind: 'state';
  value: SchemaNode;
  initial: unknown;
}

// ---- helpers ---------------------------------------------------------------

const CODEGEN_VERSION = '1';

/** Unwrap optional/nullable to the first structured/primitive inner node. */
function unwrapWrappers(node: SchemaNode): SchemaNode {
  let inner = node;
  while (inner.kind === 'optional' || inner.kind === 'nullable') {
    inner = (inner as OptionalNode | NullableNode).inner;
  }
  return inner;
}

// ---- schemaUsesDate --------------------------------------------------------
// Same recursion as Kotlin version — Date/Data both require import Foundation.

function schemaUsesDate(node: SchemaNode | null | undefined): boolean {
  if (!node) return false;
  if (node.kind === 'date' || node.kind === 'binary') return true;
  if (node.kind === 'object') {
    return Object.values((node as ObjectNode).fields).some(schemaUsesDate);
  }
  if (node.kind === 'array') return schemaUsesDate((node as ArrayNode).item);
  if (node.kind === 'optional' || node.kind === 'nullable') {
    return schemaUsesDate((node as OptionalNode | NullableNode).inner);
  }
  if (node.kind === 'record') return schemaUsesDate((node as RecordNode).value);
  if (node.kind === 'union') {
    return Object.values((node as UnionNode).variants).some((variant) =>
      Object.values(variant.fields).some(schemaUsesDate),
    );
  }
  if (node.kind === 'tuple') return (node as TupleNode).items.some(schemaUsesDate);
  if (node.kind === 'oneOf') return (node as OneOfNode).options.some(schemaUsesDate);
  return false;
}

// ---- schemaUsesBoundaryDecodeThrow -----------------------------------------

function schemaUsesBoundaryDecodeThrow(node: SchemaNode | null | undefined): boolean {
  if (!node) return false;
  if (
    node.kind === 'date' ||
    node.kind === 'binary' ||
    node.kind === 'enum' ||
    node.kind === 'int64'
  ) {
    return true;
  }
  if (node.kind === 'object') {
    return Object.values((node as ObjectNode).fields).some(schemaUsesBoundaryDecodeThrow);
  }
  if (node.kind === 'array') return schemaUsesBoundaryDecodeThrow((node as ArrayNode).item);
  if (node.kind === 'optional' || node.kind === 'nullable') {
    return schemaUsesBoundaryDecodeThrow((node as OptionalNode | NullableNode).inner);
  }
  if (node.kind === 'record') return schemaUsesBoundaryDecodeThrow((node as RecordNode).value);
  if (node.kind === 'union') {
    return Object.values((node as UnionNode).variants).some((variant) =>
      Object.values(variant.fields).some(schemaUsesBoundaryDecodeThrow),
    );
  }
  if (node.kind === 'tuple') return (node as TupleNode).items.some(schemaUsesBoundaryDecodeThrow);
  if (node.kind === 'oneOf') return (node as OneOfNode).options.some(schemaUsesBoundaryDecodeThrow);
  return false;
}

// ---- assembleSwiftContractFile ---------------------------------------------

export function assembleSwiftContractFile(parts: {
  fileName: string;
  id: string;
  hash: string;
  className: string;
  codegenVersion: string;
  typeDecls: string[];
  providerMethods: string[];
  clientMethods: string[];
  encodeDecodeFns: string[];
  memberHashPairs: string[];
  inboundImpls: string[];
  syncImpls: string[];
  streamImpls: string[];
  outboundImpls: string[];
  stateInitials: string[];
  stateFlowEntries: string[];
  needsFoundationImport: boolean;
  needsBridgeKitDecodeError: boolean;
}): EmitResult {
  const {
    fileName,
    id,
    hash,
    className,
    codegenVersion,
    typeDecls,
    providerMethods,
    clientMethods,
    encodeDecodeFns,
    memberHashPairs,
    inboundImpls,
    syncImpls,
    streamImpls,
    outboundImpls,
    stateInitials,
    stateFlowEntries,
    needsFoundationImport,
    needsBridgeKitDecodeError,
  } = parts;

  const lines: string[] = [];

  // Header
  lines.push(`// Generated by bridgekit ${codegenVersion}. DO NOT EDIT.`);
  lines.push(`// Contract: ${id}`);
  lines.push(`// Contract hash: ${hash}`);
  lines.push('');
  lines.push('import BridgeKit');
  if (needsFoundationImport) {
    lines.push('import Foundation');
  }
  if (needsBridgeKitDecodeError || encodeDecodeFns.length > 0) {
    // BridgeKitDecodeError is part of BridgeKit module; import is already covered.
    // No additional import needed — BridgeKitDecodeError is in BridgeKit.
  }
  lines.push('');

  // Type declarations (structs, enums)
  if (typeDecls.length > 0) {
    lines.push('// ---- Types -----------------------------------------------------------------');
    lines.push('');
    for (const decl of typeDecls) {
      lines.push(decl);
      lines.push('');
    }
  }

  // Provider protocol — AnyObject constraint required so BridgeContractDefinition<any P, any C>
  // satisfies P: AnyObject (class-bound existential satisfies AnyObject in Swift 5.7+).
  lines.push('// ---- Provider protocol ------------------------------------------------------');
  lines.push('');
  lines.push(`/// Native-side implementation protocol for contract '${id}'.`);
  lines.push(`protocol ${className}: AnyObject {`);
  for (const m of providerMethods) lines.push(m);
  lines.push(`}`);
  lines.push('');

  // Client protocol — same AnyObject constraint.
  lines.push('// ---- Client protocol --------------------------------------------------------');
  lines.push('');
  lines.push(`/// RN-side consumer protocol for contract '${id}'.`);
  lines.push(`protocol ${className}Client: AnyObject {`);
  for (const m of clientMethods) lines.push(m);
  lines.push(`}`);
  lines.push('');

  // Codec enum (static functions)
  if (encodeDecodeFns.length > 0) {
    lines.push('// ---- Codecs ----------------------------------------------------------------');
    lines.push('');
    lines.push(`private enum ${className}Codecs {`);
    for (const fn of encodeDecodeFns) {
      // indent each line by 4 spaces
      for (const l of fn.split('\n')) lines.push(l === '' ? '' : `    ${l}`);
      lines.push('');
    }
    lines.push('}');
    lines.push('');
  }

  // Contract definition
  lines.push('// ---- Contract definition ---------------------------------------------------');
  lines.push('');
  lines.push(
    `class ${className}Contract: BridgeContractDefinition<any ${className}, any ${className}Client> {`,
  );
  // NOTE: id/contractHash/memberHashes are stored properties on the superclass.
  // We must NOT redeclare them as let — that causes a Swift compile error.
  // Instead pass them via super.init(id:contractHash:memberHashes:).
  lines.push(`    init() {`);
  lines.push(`        super.init(`);
  lines.push(`            id: ${swiftStringLiteral(id)},`);
  lines.push(`            contractHash: ${swiftStringLiteral(hash)},`);
  lines.push(`            memberHashes: [`);
  for (let i = 0; i < memberHashPairs.length; i++) {
    const comma = i < memberHashPairs.length - 1 ? ',' : '';
    lines.push(`                ${memberHashPairs[i]}${comma}`);
  }
  lines.push(`            ]`);
  lines.push(`        )`);
  lines.push(`    }`);
  lines.push('');

  // inbound — must override the open func from BridgeContractDefinition
  lines.push(`    override func inbound(_ impl: any ${className}) -> InboundContractAdapter {`);
  lines.push(`        return ${className}InboundAdapter(impl: impl)`);
  lines.push(`    }`);
  lines.push('');

  // outbound — must override the open func from BridgeContractDefinition
  lines.push(`    override func outbound(_ caller: OutboundCaller) -> any ${className}Client {`);
  lines.push(`        return ${className}OutboundClient(caller: caller)`);
  lines.push(`    }`);
  lines.push(`}`);
  lines.push('');

  // Inbound adapter class
  lines.push(`private class ${className}InboundAdapter: InboundContractAdapter {`);
  lines.push(`    let impl: any ${className}`);
  lines.push(`    init(impl: any ${className}) { self.impl = impl }`);
  lines.push('');

  if (stateInitials.length === 0) {
    lines.push(`    var stateInitials: [String: Any?] { return [:] }`);
  } else {
    lines.push(`    var stateInitials: [String: Any?] { return [`);
    for (const entry of stateInitials) lines.push(`        ${entry}`);
    lines.push(`    ] }`);
  }
  lines.push('');

  lines.push(`    func invoke(member: String, payload: [String: Any?]?) async throws -> Any? {`);
  lines.push(`        switch member {`);
  for (const impl of inboundImpls) {
    for (const l of impl.split('\n')) lines.push(`        ${l}`);
  }
  lines.push(`        default: throw BridgeKitDecodeError(field: "member", expectedType: member)`);
  lines.push(`        }`);
  lines.push(`    }`);
  lines.push('');

  lines.push(`    func invokeSync(member: String, payload: [String: Any?]?) throws -> Any? {`);
  lines.push(`        switch member {`);
  for (const impl of syncImpls) {
    for (const l of impl.split('\n')) lines.push(`        ${l}`);
  }
  lines.push(`        default: throw BridgeKitDecodeError(field: "member", expectedType: member)`);
  lines.push(`        }`);
  lines.push(`    }`);
  lines.push('');

  // openStream: protocol requires AsyncThrowingStream<Any?, Error>
  lines.push(
    `    func openStream(member: String, payload: [String: Any?]?) -> AsyncThrowingStream<Any?, Error> {`,
  );
  lines.push(`        switch member {`);
  for (const impl of streamImpls) {
    for (const l of impl.split('\n')) lines.push(`        ${l}`);
  }
  lines.push(`        default: return AsyncThrowingStream { $0.finish() }`);
  lines.push(`        }`);
  lines.push(`    }`);
  lines.push('');

  // stateStreams(): protocol requires a function, not a computed property.
  // Body reads from impl (the provider), not from caller (which is on the outbound side).
  if (stateFlowEntries.length === 0) {
    lines.push(`    func stateStreams() -> [String: AsyncStream<Any?>] { return [:] }`);
  } else {
    lines.push(`    func stateStreams() -> [String: AsyncStream<Any?>] { return [`);
    for (let i = 0; i < stateFlowEntries.length; i++) {
      const comma = i < stateFlowEntries.length - 1 ? ',' : '';
      lines.push(`        ${stateFlowEntries[i]}${comma}`);
    }
    lines.push(`    ] }`);
  }
  lines.push(`}`);
  lines.push('');

  // Outbound client class
  lines.push(`private class ${className}OutboundClient: ${className}Client {`);
  lines.push(`    let caller: OutboundCaller`);
  lines.push(`    init(caller: OutboundCaller) { self.caller = caller }`);
  for (const impl of outboundImpls) {
    for (const l of impl.split('\n')) lines.push(`    ${l}`);
  }
  lines.push(`}`);

  return {
    fileName,
    content: `${lines.join('\n')}\n`,
  };
}

// ---- emitSwiftContract -----------------------------------------------------

export function emitSwiftContract(
  token: RawContractToken,
  _contractPackage: string,
  resolvedClassName?: string,
): EmitResult {
  const descriptor = token.descriptor;
  const id = descriptor.id;
  const hash = token.hash;
  const className = resolvedClassName ?? contractIdToClassName(id);
  const fileName = `${className}Contract.swift`;

  const typeEmitter = new SwiftTypeEmitter(className);

  const providerMethods: string[] = [];
  const clientMethods: string[] = [];
  const inboundImpls: string[] = [];
  const syncImpls: string[] = [];
  const streamImpls: string[] = [];
  const outboundImpls: string[] = [];
  const memberHashPairs: string[] = [];
  const encodeDecodeFns: string[] = [];
  const stateInitials: string[] = [];
  const stateFlowEntries: string[] = [];

  const registeredCodecs = new Set<string>();
  const registerCodecFn = (fn: string): void => {
    const m = fn.match(/^static func (encode|decode)([A-Za-z0-9_]+)\(/);
    const baseName = m ? m[2] : null;
    if (baseName && encodeDecodeFns.some((existing) => existing.includes(`encode${baseName}(`))) {
      return;
    }
    encodeDecodeFns.push(fn);
  };
  const walker = new SwiftCodecWalker(typeEmitter, className, registerCodecFn, registeredCodecs);

  const registerObjectCodec = (dataClassName: string, objNode: ObjectNode): void => {
    if (encodeDecodeFns.some((fn) => fn.includes(`encode${dataClassName}(`))) return;
    registeredCodecs.add(dataClassName);
    encodeDecodeFns.push(walker.emitObjectCodec(dataClassName, objNode));
  };

  // ---- methods ----
  for (const [memberName, rawDesc] of Object.entries(descriptor.methods)) {
    const desc = rawDesc as MethodDescRaw;
    const swiftName = escapeSwiftIdentifier(memberName);
    const memberCtx = toPascalCase(memberName);

    memberHashPairs.push(
      `${swiftStringLiteral(`methods.${memberName}`)}: ${swiftStringLiteral(hashMember(rawDesc))}`,
    );

    if (desc.kind === 'fire') {
      let paramsType = '';
      if (desc.params) {
        const dataClassName = `${memberCtx}Params`;
        const paramsResult = typeEmitter.emit(desc.params, dataClassName);
        paramsType = paramsResult.typeName;
        registerObjectCodec(paramsType, desc.params);
      }

      const paramSig = paramsType ? `_ params: ${paramsType}` : '';
      providerMethods.push(`    func ${swiftName}(${paramSig})`);
      clientMethods.push(`    func ${swiftName}(${paramSig})`);

      // inbound
      if (paramsType) {
        inboundImpls.push(
          [
            `case ${swiftStringLiteral(memberName)}:`,
            `    let decoded = try ${className}Codecs.decode${paramsType}(payload ?? [:])`,
            `    impl.${swiftName}(decoded)`,
            `    return nil`,
          ].join('\n'),
        );
      } else {
        inboundImpls.push(
          `case ${swiftStringLiteral(memberName)}: impl.${swiftName}(); return nil`,
        );
      }

      // outbound
      if (paramsType) {
        outboundImpls.push(
          [
            `func ${swiftName}(_ params: ${paramsType}) {`,
            `    caller.fire(member: ${swiftStringLiteral(memberName)}, payload: ${className}Codecs.encode${paramsType}(params))`,
            `}`,
          ].join('\n'),
        );
      } else {
        outboundImpls.push(
          `func ${swiftName}() { caller.fire(member: ${swiftStringLiteral(memberName)}, payload: nil) }`,
        );
      }
    } else if (desc.kind === 'query' || desc.kind === 'querySync') {
      let paramsType = '';
      let resultType = 'Void';

      if (desc.params) {
        const dataClassName = `${memberCtx}Params`;
        const paramsResult = typeEmitter.emit(desc.params, dataClassName);
        paramsType = paramsResult.typeName;
      }

      const resultCtx = `${memberCtx}Result`;
      if (desc.result) {
        const res = typeEmitter.emit(desc.result, resultCtx);
        resultType = res.typeName;
      }

      const paramSig = paramsType ? `_ params: ${paramsType}` : '';
      const asyncMod = desc.kind === 'query' ? 'async ' : '';

      providerMethods.push(`    func ${swiftName}(${paramSig}) ${asyncMod}throws -> ${resultType}`);
      clientMethods.push(`    func ${swiftName}(${paramSig}) ${asyncMod}throws -> ${resultType}`);

      const invokeCall = desc.kind === 'querySync' ? 'invokeSync' : 'invoke';
      const encodeParams = paramsType ? `${className}Codecs.encode${paramsType}(params)` : 'nil';
      const isNullableResult = resultType.endsWith('?');

      // inbound
      if (desc.kind === 'querySync') {
        // Provider Sync methods are declared `throws`; use `try` here.
        const inboundCallExprBase = paramsType
          ? `try impl.${swiftName}(decoded)`
          : `try impl.${swiftName}()`;
        const inboundResultExpr = desc.result
          ? buildSwiftInboundEncodeExpr(desc.result, inboundCallExprBase, resultCtx, walker)
          : inboundCallExprBase;
        const body: string[] = [`case ${swiftStringLiteral(memberName)}:`];
        if (paramsType) {
          body.push(`    let decoded = try ${className}Codecs.decode${paramsType}(payload ?? [:])`);
        }
        body.push(`    return ${inboundResultExpr}`);
        syncImpls.push(body.join('\n'));
      } else {
        const inboundCallExprBase = paramsType
          ? `impl.${swiftName}(decoded)`
          : `impl.${swiftName}()`;
        // Provider async methods are declared `async throws`; use `try await` here.
        // The outer func is also `async throws`, so `try` propagates naturally.
        const inboundResultExpr = desc.result
          ? buildSwiftInboundEncodeExpr(
              desc.result,
              `try await ${inboundCallExprBase}`,
              resultCtx,
              walker,
            )
          : `try await ${inboundCallExprBase}`;
        const body: string[] = [`case ${swiftStringLiteral(memberName)}:`];
        if (paramsType) {
          body.push(`    let decoded = try ${className}Codecs.decode${paramsType}(payload ?? [:])`);
        }
        body.push(`    return ${inboundResultExpr}`);
        inboundImpls.push(body.join('\n'));
      }

      // outbound return
      const returnLines = buildSwiftOutboundReturnLines(
        desc.result ?? null,
        resultType,
        isNullableResult,
        memberName,
        resultCtx,
        walker,
      );

      if (desc.kind === 'querySync') {
        outboundImpls.push(
          [
            `func ${swiftName}(${paramSig}) throws -> ${resultType} {`,
            `    let result = try caller.${invokeCall}(member: ${swiftStringLiteral(memberName)}, payload: ${encodeParams})`,
            ...returnLines,
            `}`,
          ].join('\n'),
        );
      } else {
        outboundImpls.push(
          [
            `func ${swiftName}(${paramSig}) async throws -> ${resultType} {`,
            `    let result = try await caller.${invokeCall}(member: ${swiftStringLiteral(memberName)}, payload: ${encodeParams})`,
            ...returnLines,
            `}`,
          ].join('\n'),
        );
      }

      if (paramsType && desc.params) {
        registerObjectCodec(paramsType, desc.params);
      }
    }
  }

  // ---- streams ----
  for (const [memberName, rawDesc] of Object.entries(descriptor.streams)) {
    const desc = rawDesc as StreamDescRaw;
    const swiftName = escapeSwiftIdentifier(memberName);
    const memberCtx = toPascalCase(memberName);
    const valueResult = typeEmitter.emit(desc.value, `${memberCtx}Value`);
    const streamType = `AsyncStream<${valueResult.typeName}>`;

    memberHashPairs.push(
      `${swiftStringLiteral(`streams.${memberName}`)}: ${swiftStringLiteral(hashMember(rawDesc))}`,
    );

    let streamParamsType = '';
    if (desc.params) {
      const dataClassName = `${memberCtx}Params`;
      const paramsResult = typeEmitter.emit(desc.params, dataClassName);
      streamParamsType = paramsResult.typeName;
      registerObjectCodec(streamParamsType, desc.params);
    }

    const paramSig = streamParamsType ? `_ params: ${streamParamsType}` : '';
    providerMethods.push(`    func ${swiftName}(${paramSig}) -> ${streamType}`);
    clientMethods.push(`    func ${swiftName}(${paramSig}) -> ${streamType}`);

    const encodeStreamParams = streamParamsType
      ? `${className}Codecs.encode${streamParamsType}(params)`
      : 'nil';

    const valueCtx = `${memberCtx}Value`;
    // caller.stream() returns AsyncThrowingStream<Any?, Error>. Bridge it to AsyncStream<T>
    // by decoding each element (walker.decodeExpr handles numeric Int/Double coercion —
    // a raw `as! Double` traps when JS sends an integer) and swallowing the error
    // (matching Kotlin Flow.catch behaviour).
    const decodeStreamItem = walker.decodeExpr('item', desc.value, valueCtx, `${swiftName}.value`);
    outboundImpls.push(
      [
        `func ${swiftName}(${paramSig}) -> ${streamType} {`,
        `    let throwing = caller.stream(member: ${swiftStringLiteral(memberName)}, payload: ${encodeStreamParams})`,
        `    return AsyncStream { cont in Task { do { for try await item in throwing { cont.yield(${decodeStreamItem}) } } catch {} ; cont.finish() } }`,
        `}`,
      ].join('\n'),
    );

    // inbound openStream: provider returns AsyncStream<T>, protocol requires AsyncThrowingStream<Any?, Error>.
    // Bridge by wrapping the provider's AsyncStream in a non-throwing stream yielded into the throwing one.
    const callExpr = streamParamsType
      ? `impl.${swiftName}(${className}Codecs.decode${streamParamsType}(payload ?? [:]))`
      : `impl.${swiftName}()`;
    if (schemaNeedsCodec(desc.value)) {
      const encodeItem = walker.encodeExpr('item', desc.value, valueCtx);
      streamImpls.push(
        [
          `case ${swiftStringLiteral(memberName)}:`,
          `    let src = ${callExpr}`,
          `    return AsyncThrowingStream { cont in Task { for await item in src { cont.yield(${encodeItem}) }; cont.finish() } }`,
        ].join('\n'),
      );
    } else {
      streamImpls.push(
        [
          `case ${swiftStringLiteral(memberName)}:`,
          `    let src = ${callExpr}`,
          `    return AsyncThrowingStream { cont in Task { for await item in src { cont.yield(item) }; cont.finish() } }`,
        ].join('\n'),
      );
    }
  }

  // ---- state ----
  for (const [memberName, rawDesc] of Object.entries(descriptor.state)) {
    const desc = rawDesc as StateDescRaw;
    const swiftName = escapeSwiftIdentifier(memberName);
    const memberCtx = toPascalCase(memberName);
    const valueResult = typeEmitter.emit(desc.value, memberCtx);

    memberHashPairs.push(
      `${swiftStringLiteral(`state.${memberName}`)}: ${swiftStringLiteral(hashMember(rawDesc))}`,
    );

    stateInitials.push(
      `${swiftStringLiteral(memberName)}: ${swiftLiteralForSchema(desc.initial, desc.value)},`,
    );

    providerMethods.push(`    var ${swiftName}: AsyncStream<${valueResult.typeName}> { get }`);
    clientMethods.push(
      `    var ${swiftName}: AsyncStream<BridgeValue<${valueResult.typeName}>> { get }`,
    );

    // stateFlowEntries are emitted inside the INBOUND adapter (no `caller`).
    // Bridge the provider's AsyncStream<T> to AsyncStream<Any?> via a wrapping stream.
    if (schemaNeedsCodec(desc.value)) {
      const encodeStateValue = walker.encodeExpr('v', desc.value, memberCtx);
      stateFlowEntries.push(
        `${swiftStringLiteral(memberName)}: AsyncStream<Any?> { cont in Task { for await v in self.impl.${swiftName} { cont.yield(${encodeStateValue}) }; cont.finish() } }`,
      );
    } else {
      stateFlowEntries.push(
        `${swiftStringLiteral(memberName)}: AsyncStream<Any?> { cont in Task { for await v in self.impl.${swiftName} { cont.yield(v) }; cont.finish() } }`,
      );
    }

    // caller.state() yields AsyncStream<BridgeValue<Any?>>. AsyncStream is an
    // invariant generic struct, so `as! AsyncStream<BridgeValue<T>>` traps at
    // runtime. Re-type element-by-element via BridgeValue.remap, decoding the
    // carried value with the walker (handles numeric coercion + composite codecs).
    const decodeStateValue = walker.decodeExpr(
      'value',
      desc.value,
      memberCtx,
      `${swiftName}.value`,
    );
    outboundImpls.push(
      [
        `var ${swiftName}: AsyncStream<BridgeValue<${valueResult.typeName}>> {`,
        `    let source = caller.state(member: ${swiftStringLiteral(memberName)})`,
        `    return AsyncStream { cont in`,
        `        let pump = Task {`,
        `            for await bv in source {`,
        `                cont.yield(bv.remap { (value: Any?) -> ${valueResult.typeName}? in try? (${decodeStateValue}) })`,
        `            }`,
        `            cont.finish()`,
        `        }`,
        `        cont.onTermination = { _ in pump.cancel() }`,
        `    }`,
        `}`,
      ].join('\n'),
    );
  }

  const needsFoundationImport =
    Object.values(descriptor.methods).some((m) => {
      const d = m as MethodDescRaw;
      return schemaUsesDate(d.params ?? null) || schemaUsesDate(d.result ?? null);
    }) ||
    Object.values(descriptor.streams).some((s) => schemaUsesDate((s as StreamDescRaw).value)) ||
    Object.values(descriptor.state).some((s) => schemaUsesDate((s as StateDescRaw).value));

  const needsBridgeKitDecodeError =
    Object.values(descriptor.methods).some((m) => {
      const d = m as MethodDescRaw;
      return schemaUsesBoundaryDecodeThrow(d.result ?? null);
    }) ||
    Object.values(descriptor.streams).some((s) =>
      schemaUsesBoundaryDecodeThrow((s as StreamDescRaw).value),
    ) ||
    Object.values(descriptor.state).some((s) =>
      schemaUsesBoundaryDecodeThrow((s as StateDescRaw).value),
    );

  return assembleSwiftContractFile({
    fileName,
    id,
    hash,
    className,
    codegenVersion: CODEGEN_VERSION,
    typeDecls: typeEmitter.getDeclarations(),
    providerMethods,
    clientMethods,
    encodeDecodeFns,
    memberHashPairs,
    inboundImpls,
    syncImpls,
    streamImpls,
    outboundImpls,
    stateInitials,
    stateFlowEntries,
    needsFoundationImport,
    needsBridgeKitDecodeError,
  });
}

// ---- outbound return expression builders -----------------------------------

function buildSwiftOutboundReturnLines(
  resultSchema: SchemaNode | null,
  resultType: string,
  isNullable: boolean,
  _memberName: string,
  resultCtx: string,
  walker: SwiftCodecWalker,
): string[] {
  if (!resultSchema || resultType === 'Void') return [`    return`];

  const innerSchema = unwrapWrappers(resultSchema);
  const isPlainCast = !schemaNeedsCodec(innerSchema);

  if (isPlainCast) {
    const bareType = resultType.replace(/\?$/, '');
    if (isNullable) {
      return [`    return result as? ${bareType}`];
    }
    return [`    return result as! ${bareType}`];
  }

  const decodeExpr = walker.boundaryDecode('result', innerSchema, resultCtx);
  if (isNullable) {
    return [`    return result == nil ? nil : (${decodeExpr})`];
  }
  return [`    return ${decodeExpr}`];
}

function buildSwiftInboundEncodeExpr(
  resultSchema: SchemaNode,
  callExpr: string,
  resultCtx: string,
  walker: SwiftCodecWalker,
): string {
  const inner = unwrapWrappers(resultSchema);
  if (inner.kind === 'void' || !schemaNeedsCodec(inner)) return callExpr;
  const isNullable = resultSchema.kind === 'optional' || resultSchema.kind === 'nullable';
  if (isNullable) {
    return `${callExpr}.map { ${walker.boundaryEncode('$0', inner, resultCtx)} }`;
  }
  return walker.boundaryEncode(callExpr, inner, resultCtx);
}
