package io.github.malopezr7.bridgekit.runtime

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.StateFlow

/**
 * Generated by the CLI per contract. Adapts a typed provider implementation to the
 * engine's untyped Map-based wire surface.
 *
 * Implementations are generated objects inside BridgeContractDefinition.inbound().
 * They must NOT be shared across binding instances — each provide() call creates one.
 */
interface InboundContractAdapter {

    /**
     * Initial state values keyed by state member name. Values are the DSL-declared
     * initial values (already encoded as wire-compatible maps/primitives).
     * The engine seeds the state store from this map at provide() time.
     */
    val stateInitials: Map<String, Any?>

    /**
     * Dispatch an async member call on the provider.
     * [member] is the DSL member name; [payload] is the decoded parameters map or null.
     * Returns the result value (will be wire-encoded by the engine) or null for fire/Unit.
     * Throws for unknown members — engine maps to METHOD_NOT_FOUND.
     */
    suspend fun invoke(member: String, payload: Map<String, Any?>?): Any?

    /**
     * Dispatch a synchronous querySync member call.
     * Constraints: in-memory lookup only; provider must not block.
     * Throws for unknown sync members.
     */
    fun invokeSync(member: String, payload: Map<String, Any?>?): Any?

    /**
     * Return the provider's Flow for the given stream member.
     * Throws for unknown stream members.
     */
    fun openStream(member: String, payload: Map<String, Any?>?): Flow<Any?>

    /**
     * Return all provider state flows, keyed by state member name.
     * The engine subscribes to these for bridge-side change propagation.
     */
    fun stateFlows(): Map<String, StateFlow<Any?>>
}
