// BindingEntry.swift
// BridgeKit iOS engine — internal representation of a live provider binding.
//
// Holds the adapter + isLive flag + per-binding stream job registry.
// registerStreamJob rechecks isLive after insert to handle the race between
// openStream's binding check and job registration.

import Foundation

// MARK: - CloseReason

/// Reason a binding was closed.
///
/// NOTE: `replacing` does NOT currently hold in-flight invokes. A
/// `replacingGraceMs = 1500` constant used to be declared here and was never
/// read by anything — the documented parking behaviour does not exist on either
/// platform. Mirrored state DOES get a grace window (`StateStore.replacingGraceMs`,
/// 250ms), which is implemented and tested; that is a different mechanism.
/// Tracked in KNOWN_ISSUES.md rather than advertised by a dead constant.
public enum CloseReason {
    /// Binding is being replaced. In-flight invokes are not parked today.
    case replacing
    /// Binding is permanently closed; all pending calls fail immediately.
    case final_
}

// MARK: - Binding protocol

/// Handle to a live provider binding returned from `BridgeKit.provide`.
public protocol Binding: AnyObject {
    var contractId: String { get }
    var scope: Scope { get }
    var isLive: Bool { get }

    /// Close this binding with the given reason. No-op if already closed.
    func close(reason: CloseReason)
}

public extension Binding {
    func close() { close(reason: .final_) }
}

// MARK: - InboundContractAdapter

/// Adapts a typed provider to the engine's untyped wire surface.
/// Implementations are generated by the CLI per contract.
public protocol InboundContractAdapter: AnyObject {
    /// Initial state values keyed by state member name.
    var stateInitials: [String: Any?] { get }

    /// Async member dispatch.
    func invoke(member: String, payload: [String: Any?]?) async throws -> Any?

    /// Sync member dispatch (in-memory reads only).
    func invokeSync(member: String, payload: [String: Any?]?) throws -> Any?

    /// Return an AsyncThrowingStream for the given stream member.
    func openStream(member: String, payload: [String: Any?]?) -> AsyncThrowingStream<Any?, Error>

    /// All provider state streams keyed by state member name.
    func stateStreams() -> [String: AsyncStream<Any?>]
}

// MARK: - BindingEntry

/// Internal live binding.
internal final class BindingEntry {

    let definition: AnyBridgeContractDefinition
    let scope: Scope
    let adapter: InboundContractAdapter
    let contractId: String

    // Guarded by the engine NSRecursiveLock (all reads/writes happen inside Router paths).
    private var _isLive: Bool = true
    var isLive: Bool { _isLive }
    private(set) var closeReason: CloseReason? = nil

    // Stream job registry — guarded by engine lock.
    private var streamJobs: [String: Task<Void, Never>] = [:]

    // State stream observation tasks (collect provider → stateStore).
    private var stateObservationTasks: [Task<Void, Never>] = []

    internal init(
        definition: AnyBridgeContractDefinition,
        scope: Scope,
        adapter: InboundContractAdapter
    ) {
        self.definition = definition
        self.scope = scope
        self.adapter = adapter
        self.contractId = definition.id
    }

    // MARK: - Lifecycle

    internal func close(reason: CloseReason) {
        guard _isLive else { return }
        closeReason = reason
        _isLive = false
        cancelAllStreamJobs()
        cancelStateObservations()
    }

    // MARK: - Stream job registry

    /// Register a stream job. Cancels immediately if the binding was already closed.
    internal func registerStreamJob(_ streamId: String, job: Task<Void, Never>) {
        streamJobs[streamId] = job
        if !_isLive {
            streamJobs.removeValue(forKey: streamId)
            job.cancel()
        }
    }

    internal func cancelStreamJob(_ streamId: String) {
        streamJobs.removeValue(forKey: streamId)?.cancel()
    }

    internal func cancelAllStreamJobs() {
        for (_, job) in streamJobs { job.cancel() }
        streamJobs.removeAll()
    }

    // MARK: - State observation tasks

    internal func addStateObservation(_ task: Task<Void, Never>) {
        stateObservationTasks.append(task)
    }

    internal func cancelStateObservations() {
        for task in stateObservationTasks { task.cancel() }
        stateObservationTasks.removeAll()
    }
}
