// Generated by bridgekit 1. DO NOT EDIT.
// Contract: connect.host
// Contract hash: 5b209568

package io.github.malopezr7.bridgekit.contracts.connect.host

import io.github.malopezr7.bridgekit.runtime.BridgeContractDefinition
import io.github.malopezr7.bridgekit.runtime.BridgeValue
import io.github.malopezr7.bridgekit.runtime.InboundContractAdapter
import io.github.malopezr7.bridgekit.runtime.OutboundCaller

// ---- Types ----------------------------------------------------------------

data class InstallEsimParams(
    val url: String,
    val iccId: String
)

enum class InstallEsimResult(val wireValue: String) {
    /** Wire value: "success" */
    SUCCESS("success"),
    /** Wire value: "already-installed" */
    ALREADY_INSTALLED("already-installed"),
    /** Wire value: "cancelled" */
    CANCELLED("cancelled"),
    /** Wire value: "error" */
    ERROR("error");

    companion object {
        /** Decode a wire value, returning null for unknown values (forward-skew policy). */
        fun fromWire(value: String): InstallEsimResult? = values().find { it.wireValue == value }
    }
}

data class GetDeviceInfoResult(
    val model: String,
    val osVersion: String
)

data class PickMediaParams(
    val allowMultiple: Boolean? = null
)

sealed class PickMediaResult {
    abstract val kind: String
    data class Image(
        override val kind: String = "image",
        val uri: String,
        val width: Double,
        val height: Double
    ) : PickMediaResult()
    data class Video(
        override val kind: String = "video",
        val uri: String,
        val durationMs: Double
    ) : PickMediaResult()
}

data class TrackEventParams(
    val name: String,
    val params: Any? = null
)

data class Connectivity(
    val online: Boolean
)

// ---- Provider interface -------------------------------------------------------

/** Native-side implementation interface for contract 'connect.host'. */
interface ConnectHost {
    fun showLogin()
    suspend fun isLoggedIn(): Boolean
    suspend fun installEsim(params: InstallEsimParams): InstallEsimResult
    fun getDeviceInfo(): GetDeviceInfoResult
    suspend fun pickMedia(params: PickMediaParams): PickMediaResult?
    fun trackEvent(params: TrackEventParams)
    fun otpCodes(): kotlinx.coroutines.flow.Flow<String>
    val connectivity: kotlinx.coroutines.flow.MutableStateFlow<Connectivity>
}

// ---- Client interface ---------------------------------------------------------

/** RN-side consumer interface for contract 'connect.host'. */
interface ConnectHostClient {
    fun showLogin()
    suspend fun isLoggedIn(): Boolean
    suspend fun installEsim(params: InstallEsimParams): InstallEsimResult
    fun getDeviceInfo(): GetDeviceInfoResult
    suspend fun pickMedia(params: PickMediaParams): PickMediaResult?
    fun trackEvent(params: TrackEventParams)
    fun otpCodes(): kotlinx.coroutines.flow.Flow<String>
    val connectivity: kotlinx.coroutines.flow.StateFlow<io.github.malopezr7.bridgekit.runtime.BridgeValue<Connectivity>>
}

// ---- Codecs -------------------------------------------------------------------

private object ConnectHostCodecs {
    fun encodeInstallEsimParams(value: InstallEsimParams): Map<String, Any?> {
        val map = mutableMapOf<String, Any?>()
        map["url"] = value.url
        map["iccId"] = value.iccId
        return map
    }
    
    fun decodeInstallEsimParams(raw: Map<*, *>): InstallEsimParams = InstallEsimParams(
        url = (raw["url"] as? String) ?: "",
        iccId = (raw["iccId"] as? String) ?: "",
    )

    fun encodeGetDeviceInfoResult(value: GetDeviceInfoResult): Map<String, Any?> {
        val map = mutableMapOf<String, Any?>()
        map["model"] = value.model
        map["osVersion"] = value.osVersion
        return map
    }
    
    fun decodeGetDeviceInfoResult(raw: Map<*, *>): GetDeviceInfoResult = GetDeviceInfoResult(
        model = (raw["model"] as? String) ?: "",
        osVersion = (raw["osVersion"] as? String) ?: "",
    )

    fun encodePickMediaParams(value: PickMediaParams): Map<String, Any?> {
        val map = mutableMapOf<String, Any?>()
        value.allowMultiple?.let { map["allowMultiple"] = it }
        return map
    }
    
    fun decodePickMediaParams(raw: Map<*, *>): PickMediaParams = PickMediaParams(
        allowMultiple = if (raw["allowMultiple"] == null) null else raw["allowMultiple"] as? Boolean ?: false,
    )

    fun encodeTrackEventParams(value: TrackEventParams): Map<String, Any?> {
        val map = mutableMapOf<String, Any?>()
        map["name"] = value.name
        map["params"] = value.params
        return map
    }
    
    fun decodeTrackEventParams(raw: Map<*, *>): TrackEventParams = TrackEventParams(
        name = (raw["name"] as? String) ?: "",
        params = raw["params"],
    )

}

// ---- Contract definition ------------------------------------------------------

object ConnectHostContract : BridgeContractDefinition<ConnectHost, ConnectHostClient>(
    id = "connect.host",
    contractHash = "5b209568",
    memberHashes = mapOf(
        "methods.showLogin" to "f40d63ff",
        "methods.isLoggedIn" to "8e710288",
        "methods.installEsim" to "3e20dca8",
        "methods.getDeviceInfo" to "facfdb98",
        "methods.pickMedia" to "7a01dd78",
        "methods.trackEvent" to "e2406218",
        "streams.otpCodes" to "872b3628",
        "state.connectivity" to "0f6fdedf"
    )
) {

    override fun inbound(impl: ConnectHost): InboundContractAdapter =
        object : InboundContractAdapter {
            override val stateInitials: Map<String, Any?> = mapOf(
                "connectivity" to mapOf("online" to false),
            )

            override suspend fun invoke(member: String, payload: Map<String, Any?>?): Any? =
                when (member) {
                "showLogin" -> { impl.showLogin(); null }
                "isLoggedIn" -> {
                    impl.isLoggedIn()
                }
                "installEsim" -> {
                    val decoded = ConnectHostCodecs.decodeInstallEsimParams(payload ?: emptyMap<String, Any?>())
                    impl.installEsim(decoded)
                }
                "getDeviceInfo" -> {
                    ConnectHostCodecs.encodeGetDeviceInfoResult(impl.getDeviceInfo())
                }
                "pickMedia" -> {
                    val decoded = ConnectHostCodecs.decodePickMediaParams(payload ?: emptyMap<String, Any?>())
                    impl.pickMedia(decoded)
                }
                "trackEvent" -> {
                    val decoded = ConnectHostCodecs.decodeTrackEventParams(payload ?: emptyMap<String, Any?>())
                    impl.trackEvent(decoded)
                    null
                }
                    else -> throw IllegalArgumentException("Unknown member: $member")
                }

            override fun invokeSync(member: String, payload: Map<String, Any?>?): Any? =
                invoke_sync(member, payload)

            private fun invoke_sync(member: String, payload: Map<String, Any?>?): Any? =
                when (member) {
                    "getDeviceInfo" -> {
                        ConnectHostCodecs.encodeGetDeviceInfoResult(impl.getDeviceInfo())
                    }
                    else -> throw IllegalArgumentException("Unknown sync member: $member")
                }

            override fun openStream(member: String, payload: Map<String, Any?>?): kotlinx.coroutines.flow.Flow<Any?> =
                when (member) {
                    "otpCodes" -> @Suppress("UNCHECKED_CAST") impl.otpCodes() as kotlinx.coroutines.flow.Flow<Any?>
                    else -> throw IllegalArgumentException("Unknown stream: $member")
                }

            override fun stateFlows(): Map<String, kotlinx.coroutines.flow.StateFlow<Any?>> =
                mapOf(
                    "connectivity" to @Suppress("UNCHECKED_CAST") impl.connectivity as kotlinx.coroutines.flow.StateFlow<Any?>
                )
        }

    override fun outbound(caller: OutboundCaller): ConnectHostClient =
        object : ConnectHostClient {
                override fun showLogin() { caller.invokeSync("showLogin", null) }
                override suspend fun isLoggedIn(): Boolean {
                    val result = caller.invoke("isLoggedIn", null)
                    @Suppress("UNCHECKED_CAST")
                    return result as? Boolean ?: throw IllegalStateException("Unexpected null result for isLoggedIn")
                }
                override suspend fun installEsim(params: InstallEsimParams): InstallEsimResult {
                    val result = caller.invoke("installEsim", ConnectHostCodecs.encodeInstallEsimParams(params))
                    @Suppress("UNCHECKED_CAST")
                    return result as? InstallEsimResult ?: throw IllegalStateException("Unexpected null result for installEsim")
                }
                override fun getDeviceInfo(): GetDeviceInfoResult {
                    val result = caller.invokeSync("getDeviceInfo", null)
                    @Suppress("UNCHECKED_CAST")
                    return result as? GetDeviceInfoResult ?: throw IllegalStateException("Unexpected null result for getDeviceInfo")
                }
                override suspend fun pickMedia(params: PickMediaParams): PickMediaResult? {
                    val result = caller.invoke("pickMedia", ConnectHostCodecs.encodePickMediaParams(params))
                    @Suppress("UNCHECKED_CAST")
                    return result as? PickMediaResult
                }
                override fun trackEvent(params: TrackEventParams) {
                    caller.invokeSync("trackEvent", ConnectHostCodecs.encodeTrackEventParams(params))
                }
                override fun otpCodes(): kotlinx.coroutines.flow.Flow<String> =
                    @Suppress("UNCHECKED_CAST") caller.stream("otpCodes", null) as kotlinx.coroutines.flow.Flow<String>
                override val connectivity: kotlinx.coroutines.flow.StateFlow<io.github.malopezr7.bridgekit.runtime.BridgeValue<Connectivity>>
                    get() = @Suppress("UNCHECKED_CAST") caller.state("connectivity") as kotlinx.coroutines.flow.StateFlow<io.github.malopezr7.bridgekit.runtime.BridgeValue<Connectivity>>
        }
}
