// Generated by bridgekit 1. DO NOT EDIT.
// Contract: w2.parity.test
// Contract hash: w2paritytest1
// NOTE: This file is hand-placed in test sources to prove Kotlin round-trip for
// the 6 W2 nitro-parity types (int64, date, binary, enum, tuple, oneOf).

package com.bridgekit.contracts.w2parity

import com.bridgekit.runtime.BridgeContractDefinition
import com.bridgekit.runtime.BridgeValue
import com.bridgekit.runtime.BridgeKitDecodeException
import com.bridgekit.runtime.InboundContractAdapter
import com.bridgekit.runtime.OutboundCaller
import java.time.Instant

// ---- Types ----------------------------------------------------------------

enum class GetColorResult(val wireValue: Int) {
    Red(0),
    Green(1),
    Blue(2);
    companion object {
        fun fromWire(value: Int): GetColorResult? = when (value) {
            0 -> Red
            1 -> Green
            2 -> Blue
            else -> null
        }
    }
}

data class GetPairResult(
    val v0: String,
    val v1: Double
)

sealed class GetValueResult {
    data class Opt0(val value: String) : GetValueResult()
    data class Opt1(val value: Double) : GetValueResult()
}

// ---- Provider interface -------------------------------------------------------

/** Native-side implementation interface for contract 'w2.parity.test'. */
interface W2ParityTest {
    suspend fun getCounter(): Long
    suspend fun getTimestamp(): Instant
    suspend fun getBytes(): ByteArray
    suspend fun getColor(): GetColorResult
    suspend fun getPair(): GetPairResult
    suspend fun getValue(): GetValueResult
}

// ---- Client interface ---------------------------------------------------------

/** RN-side consumer interface for contract 'w2.parity.test'. */
interface W2ParityTestClient {
    suspend fun getCounter(): Long
    suspend fun getTimestamp(): Instant
    suspend fun getBytes(): ByteArray
    suspend fun getColor(): GetColorResult
    suspend fun getPair(): GetPairResult
    suspend fun getValue(): GetValueResult
}

// ---- Codecs (internal-visibility for test access) -----------------------------

internal object W2ParityTestCodecs {
    fun encodeGetPairResult(value: GetPairResult): List<Any?> {
        return listOf(
            value.v0,
            value.v1,
        )
    }

    fun decodeGetPairResult(raw: List<*>): GetPairResult {
        if (raw.size < 2) throw BridgeKitDecodeException("tuple", "GetPairResult")
        val v0 = (raw[0] as? String) ?: throw BridgeKitDecodeException("v0", "String")
        val v1 = when (val v = raw[1]) { is Number -> v.toDouble(); else -> throw BridgeKitDecodeException("v1", "Double") }
        return GetPairResult(v0 = v0, v1 = v1)
    }

    fun encodeGetValueResult(value: GetValueResult): Map<String, Any?> = when (value) {
        is GetValueResult.Opt0 -> mapOf("@t" to "string:2ce29730", "@v" to value.value)
        is GetValueResult.Opt1 -> mapOf("@t" to "number:18e41cc0", "@v" to value.value)
    }

    fun decodeGetValueResult(raw: Map<*, *>): GetValueResult {
        val tag = raw["@t"] as? String ?: throw BridgeKitDecodeException("@t", "GetValueResult")
        val v = raw["@v"]
        return when (tag) {
            "string:2ce29730" -> GetValueResult.Opt0((v as? String) ?: throw BridgeKitDecodeException("opt0", "String"))
            "number:18e41cc0" -> GetValueResult.Opt1(when (val v = v) { is Number -> v.toDouble(); else -> throw BridgeKitDecodeException("opt1", "Double") })
            else -> throw BridgeKitDecodeException("@t=$tag", "GetValueResult")
        }
    }
}

// ---- Contract definition ------------------------------------------------------

object W2ParityTestContract : BridgeContractDefinition<W2ParityTest, W2ParityTestClient>(
    id = "w2.parity.test",
    contractHash = "w2paritytest1",
    memberHashes = mapOf(
        "methods.getCounter" to "731ebed8",
        "methods.getTimestamp" to "274cfae8",
        "methods.getBytes" to "c4e94928",
        "methods.getColor" to "4f9741ef",
        "methods.getPair" to "e924ecc0",
        "methods.getValue" to "ae60b0c8"
    )
) {

    override fun inbound(impl: W2ParityTest): InboundContractAdapter =
        object : InboundContractAdapter {
            override val stateInitials: Map<String, Any?> = mapOf()

            override suspend fun invoke(member: String, payload: Map<String, Any?>?): Any? =
                when (member) {
                    "getCounter" -> impl.getCounter().toString()
                    "getTimestamp" -> impl.getTimestamp()
                    "getBytes" -> impl.getBytes()
                    "getColor" -> impl.getColor()
                    "getPair" -> W2ParityTestCodecs.encodeGetPairResult(impl.getPair())
                    "getValue" -> W2ParityTestCodecs.encodeGetValueResult(impl.getValue())
                    else -> throw IllegalArgumentException("Unknown member: $member")
                }

            override fun invokeSync(member: String, payload: Map<String, Any?>?): Any? =
                when (member) {
                    else -> throw IllegalArgumentException("Unknown sync member: $member")
                }

            override fun openStream(
                member: String,
                payload: Map<String, Any?>?,
            ): kotlinx.coroutines.flow.Flow<Any?> =
                when (member) {
                    else -> throw IllegalArgumentException("Unknown stream: $member")
                }

            override fun stateFlows(): Map<String, kotlinx.coroutines.flow.StateFlow<Any?>> = mapOf()
        }

    override fun outbound(caller: OutboundCaller): W2ParityTestClient =
        object : W2ParityTestClient {
            override suspend fun getCounter(): Long {
                val result = caller.invoke("getCounter", null)
                @Suppress("UNCHECKED_CAST")
                return (result as? String)?.toLong()
                    ?: throw IllegalStateException("Unexpected null result for getCounter")
            }

            override suspend fun getTimestamp(): Instant {
                val result = caller.invoke("getTimestamp", null)
                @Suppress("UNCHECKED_CAST")
                return result as? Instant ?: throw IllegalStateException("Unexpected null result for getTimestamp")
            }

            override suspend fun getBytes(): ByteArray {
                val result = caller.invoke("getBytes", null)
                @Suppress("UNCHECKED_CAST")
                return result as? ByteArray ?: throw IllegalStateException("Unexpected null result for getBytes")
            }

            override suspend fun getColor(): GetColorResult {
                val result = caller.invoke("getColor", null)
                @Suppress("UNCHECKED_CAST")
                return result as? GetColorResult
                    ?: throw IllegalStateException("Unexpected null result for getColor")
            }

            override suspend fun getPair(): GetPairResult {
                val result = caller.invoke("getPair", null)
                @Suppress("UNCHECKED_CAST")
                return W2ParityTestCodecs.decodeGetPairResult(result as List<*>)
            }

            override suspend fun getValue(): GetValueResult {
                val result = caller.invoke("getValue", null)
                @Suppress("UNCHECKED_CAST")
                return W2ParityTestCodecs.decodeGetValueResult(result as Map<*, *>)
            }
        }
}
