// ---------------------------------------------------------------------------
// check.ts — --check mode: compare generated output against existing out-dir
// ---------------------------------------------------------------------------

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';

import type { EmitResult } from './emit/kotlin.js';
import { diffLocks, type LockFile } from './lock.js';

export interface CheckDiff {
  file: string;
  reason: string;
}

const GENERATED_FILE_MARKER = '// Generated by bridgekit ';

export function isBridgeKitGeneratedFile(filePath: string): boolean {
  try {
    return readFileSync(filePath, 'utf8').startsWith(GENERATED_FILE_MARKER);
  } catch {
    return false;
  }
}

export function listBridgeKitGeneratedFiles(outDir: string): string[] {
  if (!existsSync(outDir)) return [];

  return readdirSync(outDir)
    .filter((fileName) => isBridgeKitGeneratedFile(path.join(outDir, fileName)))
    .sort();
}

/**
 * Compare freshly generated output against the existing out-dir.
 * Returns list of diffs (empty = no drift).
 */
export function checkDrift(
  emitResults: EmitResult[],
  newLock: LockFile,
  outDir: string,
): CheckDiff[] {
  const diffs: CheckDiff[] = [];

  // Check Kotlin files
  for (const result of emitResults) {
    const existingPath = path.join(outDir, result.fileName);
    if (!existsSync(existingPath)) {
      diffs.push({ file: result.fileName, reason: 'file missing from out-dir' });
      continue;
    }
    const existing = readFileSync(existingPath, 'utf8');
    if (normalizeContent(existing) !== normalizeContent(result.content)) {
      diffs.push({ file: result.fileName, reason: 'content differs' });
    }
  }

  const expectedFiles = new Set(emitResults.map((result) => result.fileName));
  for (const fileName of listBridgeKitGeneratedFiles(outDir)) {
    if (!expectedFiles.has(fileName)) {
      diffs.push({ file: fileName, reason: 'extra generated file in out-dir' });
    }
  }

  // Check lock
  const lockPath = path.join(outDir, 'bridgekit.lock');
  if (!existsSync(lockPath)) {
    diffs.push({ file: 'bridgekit.lock', reason: 'lock file missing from out-dir' });
  } else {
    let existingLock: LockFile | null = null;
    try {
      existingLock = JSON.parse(readFileSync(lockPath, 'utf8')) as LockFile;
    } catch {
      diffs.push({ file: 'bridgekit.lock', reason: 'lock file is malformed JSON' });
    }
    if (existingLock) {
      const lockDiffs = diffLocks(newLock, existingLock);
      for (const d of lockDiffs) {
        diffs.push({ file: 'bridgekit.lock', reason: `contract '${d.contract}': ${d.reason}` });
      }
    }
  }

  return diffs;
}

function normalizeContent(content: string): string {
  return content.replace(/\r\n/g, '\n').trim();
}
