// Generated by bridgekit 1. DO NOT EDIT.
// Contract: hardening.fixture
// Source: packages/cli/tests/fixtures/bridgekit/hardening-fixture.contract.ts
// Statically committed compile gate — codegen regressions surface here in CI.

package io.github.malopezr7.bridgekit.contracts.hardening

import io.github.malopezr7.bridgekit.runtime.BridgeContractDefinition
import io.github.malopezr7.bridgekit.runtime.BridgeKitDecodeException
import io.github.malopezr7.bridgekit.runtime.BridgeValue
import io.github.malopezr7.bridgekit.runtime.InboundContractAdapter
import io.github.malopezr7.bridgekit.runtime.OutboundCaller
import kotlinx.coroutines.flow.map

// ---- Types ----------------------------------------------------------------

data class GetUserByIdParams(
    val id: String,
)

data class GetUserByIdResult(
    val userId: String,
    val name: String,
    val score: Double,
)

data class NotifyParams(
    val message: String,
)

data class TickStreamValue(
    val tick: Double,
)

// Nested object types for the codec round-trip gate. The codec recurses through
// the nested type exactly as the CodecWalker emits it.

data class GetNestedAddressResultAddress(
    val city: String,
)

data class GetNestedAddressResult(
    val address: GetNestedAddressResultAddress,
)

// ---- Provider interface -------------------------------------------------------

/** Native-side implementation interface for contract 'hardening.fixture'. */
interface HardeningFixture {
    suspend fun getUserById(params: GetUserByIdParams): GetUserByIdResult
    fun notify(params: NotifyParams)
    fun tickStream(): kotlinx.coroutines.flow.Flow<TickStreamValue>
    val status: kotlinx.coroutines.flow.MutableStateFlow<String>
    val count: kotlinx.coroutines.flow.MutableStateFlow<Double>
}

// ---- Client interface ---------------------------------------------------------

/** RN-side consumer interface for contract 'hardening.fixture'. */
interface HardeningFixtureClient {
    suspend fun getUserById(params: GetUserByIdParams): GetUserByIdResult
    fun notify(params: NotifyParams)
    fun tickStream(): kotlinx.coroutines.flow.Flow<TickStreamValue>
    val status: kotlinx.coroutines.flow.StateFlow<BridgeValue<String>>
    val count: kotlinx.coroutines.flow.StateFlow<BridgeValue<Double>>
}

// ---- Codecs -------------------------------------------------------------------

internal object HardeningFixtureCodecs {
    fun encodeGetUserByIdParams(value: GetUserByIdParams): Map<String, Any?> {
        val map = mutableMapOf<String, Any?>()
        map["id"] = value.id
        return map
    }

    fun decodeGetUserByIdParams(raw: Map<*, *>): GetUserByIdParams = GetUserByIdParams(
        id = (raw["id"] as? String) ?: throw BridgeKitDecodeException("id", "String"),
    )

    fun encodeGetUserByIdResult(value: GetUserByIdResult): Map<String, Any?> {
        val map = mutableMapOf<String, Any?>()
        map["userId"] = value.userId
        map["name"] = value.name
        map["score"] = value.score
        return map
    }

    fun decodeGetUserByIdResult(raw: Map<*, *>): GetUserByIdResult = GetUserByIdResult(
        userId = (raw["userId"] as? String) ?: throw BridgeKitDecodeException("userId", "String"),
        name = (raw["name"] as? String) ?: throw BridgeKitDecodeException("name", "String"),
        score = when (val v = raw["score"]) { is Number -> v.toDouble(); else -> throw BridgeKitDecodeException("score", "Double") },
    )

    fun encodeNotifyParams(value: NotifyParams): Map<String, Any?> {
        val map = mutableMapOf<String, Any?>()
        map["message"] = value.message
        return map
    }

    fun decodeNotifyParams(raw: Map<*, *>): NotifyParams = NotifyParams(
        message = (raw["message"] as? String) ?: throw BridgeKitDecodeException("message", "String"),
    )

    fun encodeTickStreamValue(value: TickStreamValue): Map<String, Any?> {
        val map = mutableMapOf<String, Any?>()
        map["tick"] = value.tick
        return map
    }

    fun decodeTickStreamValue(raw: Map<*, *>): TickStreamValue = TickStreamValue(
        tick = when (val v = raw["tick"]) { is Number -> v.toDouble(); else -> throw BridgeKitDecodeException("tick", "Double") },
    )

    // Nested object codec: encode recurses into encodeGetNestedAddressResultAddress (Map on wire);
    // decode recurses into decodeGetNestedAddressResultAddress (Map → data class).

    fun encodeGetNestedAddressResultAddress(value: GetNestedAddressResultAddress): Map<String, Any?> {
        val map = mutableMapOf<String, Any?>()
        map["city"] = value.city
        return map
    }

    fun decodeGetNestedAddressResultAddress(raw: Map<*, *>): GetNestedAddressResultAddress = GetNestedAddressResultAddress(
        city = (raw["city"] as? String) ?: throw BridgeKitDecodeException("city", "String"),
    )

    fun encodeGetNestedAddressResult(value: GetNestedAddressResult): Map<String, Any?> {
        val map = mutableMapOf<String, Any?>()
        map["address"] = encodeGetNestedAddressResultAddress(value.address)
        return map
    }

    fun decodeGetNestedAddressResult(raw: Map<*, *>): GetNestedAddressResult = GetNestedAddressResult(
        address = decodeGetNestedAddressResultAddress(
            raw["address"] as? Map<*, *>
                ?: throw BridgeKitDecodeException("address", "GetNestedAddressResultAddress"),
        ),
    )
}

// ---- Contract definition ------------------------------------------------------

object HardeningFixtureContract : BridgeContractDefinition<HardeningFixture, HardeningFixtureClient>(
    id = "hardening.fixture",
    contractHash = "deadbeef12345678",
    memberHashes = mapOf(
        "methods.getUserById" to "c9ea4e08",
        "methods.notify" to "6d063af8",
        "streams.tickStream" to "5a47dddf",
        "state.status" to "1c556b30",
        "state.count" to "b4c77128",
    ),
) {

    override fun inbound(impl: HardeningFixture): InboundContractAdapter =
        object : InboundContractAdapter {
            override val stateInitials: Map<String, Any?> = mapOf(
                "status" to "idle",
                "count" to 0,
            )

            override suspend fun invoke(member: String, payload: Map<String, Any?>?): Any? =
                when (member) {
                    "getUserById" -> {
                        val decoded = HardeningFixtureCodecs.decodeGetUserByIdParams(
                            payload ?: emptyMap<String, Any?>(),
                        )
                        HardeningFixtureCodecs.encodeGetUserByIdResult(impl.getUserById(decoded))
                    }
                    "notify" -> {
                        val decoded = HardeningFixtureCodecs.decodeNotifyParams(
                            payload ?: emptyMap<String, Any?>(),
                        )
                        impl.notify(decoded)
                        null
                    }
                    else -> throw IllegalArgumentException("Unknown member: $member")
                }

            override fun invokeSync(member: String, payload: Map<String, Any?>?): Any? =
                throw IllegalArgumentException("Unknown sync member: $member")

            override fun openStream(
                member: String,
                payload: Map<String, Any?>?,
            ): kotlinx.coroutines.flow.Flow<Any?> =
                when (member) {
                    "tickStream" ->
                        // Encode each stream item via the codec so Router.kt receives
                        // an AnyMap and can forward it as { "v" to encodedMap } to JS.
                        @Suppress("UNCHECKED_CAST")
                        (impl.tickStream().map { item ->
                            HardeningFixtureCodecs.encodeTickStreamValue(item) as Any?
                        })
                    else -> throw IllegalArgumentException("Unknown stream: $member")
                }

            override fun stateFlows(): Map<String, kotlinx.coroutines.flow.StateFlow<Any?>> =
                mapOf(
                    "status" to
                        @Suppress("UNCHECKED_CAST")
                        impl.status as kotlinx.coroutines.flow.StateFlow<Any?>,
                    "count" to
                        @Suppress("UNCHECKED_CAST")
                        impl.count as kotlinx.coroutines.flow.StateFlow<Any?>,
                )
        }

    override fun outbound(caller: OutboundCaller): HardeningFixtureClient =
        object : HardeningFixtureClient {
            override suspend fun getUserById(params: GetUserByIdParams): GetUserByIdResult {
                val result = caller.invoke(
                    "getUserById",
                    HardeningFixtureCodecs.encodeGetUserByIdParams(params),
                )
                @Suppress("UNCHECKED_CAST")
                return HardeningFixtureCodecs.decodeGetUserByIdResult(result as Map<*, *>)
            }

            override fun notify(params: NotifyParams) {
                caller.fire("notify", HardeningFixtureCodecs.encodeNotifyParams(params))
            }

            override fun tickStream(): kotlinx.coroutines.flow.Flow<TickStreamValue> =
                @Suppress("UNCHECKED_CAST")
                caller.stream("tickStream", null) as kotlinx.coroutines.flow.Flow<TickStreamValue>

            override val status: kotlinx.coroutines.flow.StateFlow<BridgeValue<String>>
                get() =
                    @Suppress("UNCHECKED_CAST")
                    caller.state("status") as kotlinx.coroutines.flow.StateFlow<BridgeValue<String>>

            override val count: kotlinx.coroutines.flow.StateFlow<BridgeValue<Double>>
                get() =
                    @Suppress("UNCHECKED_CAST")
                    caller.state("count") as kotlinx.coroutines.flow.StateFlow<BridgeValue<Double>>
        }
}
