import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const cliRoot = process.cwd();
const repoRoot = path.resolve(cliRoot, '../..');
const cliEntry = path.join(cliRoot, 'dist/index.js');

function runCli(args: string[], cwd = repoRoot) {
  return spawnSync(process.execPath, [cliEntry, ...args], {
    cwd,
    encoding: 'utf8',
  });
}

function writeContract(filePath: string, contractId: string): void {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(
    filePath,
    `import { defineContract, t } from '@malopezr7/bridgekit/contract';
export const Demo = defineContract('${contractId}', {
  methods: {
    ping: t.query(t.object({ value: t.string() }), t.string()),
  },
});
`,
    'utf8',
  );
}

describe('generate orphan safety', () => {
  let tempDir: string;

  beforeEach(() => {
    mkdirSync(path.join(cliRoot, 'build'), { recursive: true });
    tempDir = mkdtempSync(path.join(cliRoot, 'build/generate-orphans-'));
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('deletes only BridgeKit-generated orphan files after a contract rename', () => {
    const contractsDir = path.join(tempDir, 'contracts');
    const outDir = path.join(tempDir, 'generated');
    const contractFile = path.join(contractsDir, 'demo.contract.ts');
    const userFile = path.join(outDir, 'UserNotes.kt');

    writeContract(contractFile, 'demo.old');

    const first = runCli([
      'generate',
      '--contracts',
      `${contractsDir}/*.contract.ts`,
      '--out-dir',
      outDir,
      '--platform',
      'kotlin',
      '--package',
      'com.bridgekit.generated',
    ]);
    expect(first.status).toBe(0);
    expect(existsSync(path.join(outDir, 'DemoOldContract.kt'))).toBe(true);

    writeFileSync(userFile, 'package com.bridgekit.generated\n\nclass UserNotes\n', 'utf8');
    writeContract(contractFile, 'demo.new');

    const second = runCli([
      'generate',
      '--contracts',
      `${contractsDir}/*.contract.ts`,
      '--out-dir',
      outDir,
      '--platform',
      'kotlin',
      '--package',
      'com.bridgekit.generated',
    ]);
    expect(second.status).toBe(0);

    expect(existsSync(path.join(outDir, 'DemoNewContract.kt'))).toBe(true);
    expect(existsSync(path.join(outDir, 'DemoOldContract.kt'))).toBe(false);
    expect(readFileSync(userFile, 'utf8')).toContain('class UserNotes');
  });

  it('check mode reports extra BridgeKit-generated files in the output directory', () => {
    const contractsDir = path.join(tempDir, 'contracts');
    const outDir = path.join(tempDir, 'generated');
    const contractFile = path.join(contractsDir, 'demo.contract.ts');

    writeContract(contractFile, 'demo.current');
    const generate = runCli([
      'generate',
      '--contracts',
      `${contractsDir}/*.contract.ts`,
      '--out-dir',
      outDir,
      '--platform',
      'kotlin',
      '--package',
      'com.bridgekit.generated',
    ]);
    expect(generate.status).toBe(0);

    writeFileSync(
      path.join(outDir, 'DemoOldContract.kt'),
      '// Generated by bridgekit 0.0.0. DO NOT EDIT.\n// Contract: demo.old\n',
      'utf8',
    );

    const check = runCli([
      'generate',
      '--check',
      '--contracts',
      `${contractsDir}/*.contract.ts`,
      '--out-dir',
      outDir,
      '--platform',
      'kotlin',
      '--package',
      'com.bridgekit.generated',
    ]);

    expect(check.status).toBe(1);
    expect(check.stderr).toContain('DemoOldContract.kt');
    expect(check.stderr).toContain('extra generated file');
  });

  it('check mode fails when the contracts glob matches zero files', () => {
    const result = runCli([
      'generate',
      '--check',
      '--contracts',
      path.join(tempDir, 'missing/**/*.contract.ts'),
      '--out-dir',
      path.join(tempDir, 'generated'),
      '--platform',
      'kotlin',
      '--package',
      'com.bridgekit.generated',
    ]);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('matched zero contract files');
  });
});
