import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { afterEach, beforeAll, beforeEach, describe, expect, jest, test } from '@jest/globals';

type RunBridgekitCommand = (args: string[]) => Promise<number>;

const cliRoot = process.cwd();
let runBridgekitCommand: RunBridgekitCommand;
let tempDir: string;
let stderrSpy: ReturnType<typeof jest.spyOn>;

function writeContract(filePath: string, contractId: string): void {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(
    filePath,
    `import { defineContract, t } from '@malopezr7/bridgekit/contract';
export const Demo = defineContract('${contractId}', {
  methods: {
    ping: t.query(t.object({ value: t.string() }), t.string()),
  },
});
`,
    'utf8',
  );
}

function generateArgs(contracts: string, outDir: string, check = false): string[] {
  return [
    'generate',
    ...(check ? ['--check'] : []),
    '--contracts',
    contracts,
    '--out-dir',
    outDir,
    '--platform',
    'kotlin',
    '--package',
    'com.bridgekit.generated',
  ];
}

describe('generate --check safety', () => {
  beforeAll(async () => {
    const originalArgv = process.argv;
    const stdoutSpy = jest.spyOn(process.stdout, 'write').mockImplementation(() => true);
    const exitSpy = jest
      .spyOn(process, 'exit')
      .mockImplementation((() => undefined) as unknown as typeof process.exit);
    process.argv = ['node', 'bridgekit'];

    ({ runBridgekitCommand } = require('../index') as {
      runBridgekitCommand: RunBridgekitCommand;
    });
    await Promise.resolve();

    process.argv = originalArgv;
    stdoutSpy.mockRestore();
    exitSpy.mockRestore();
  });

  beforeEach(() => {
    mkdirSync(path.join(cliRoot, 'build'), { recursive: true });
    tempDir = mkdtempSync(path.join(cliRoot, 'build/generate-check-safety-'));
    stderrSpy = jest.spyOn(process.stderr, 'write').mockImplementation(() => true);
  });

  afterEach(() => {
    stderrSpy.mockRestore();
    rmSync(tempDir, { recursive: true, force: true });
  });

  test('fails stale-output checks when matched files export zero BridgeContract tokens', async () => {
    const contractsDir = path.join(tempDir, 'contracts');
    const contractFile = path.join(contractsDir, 'demo.contract.ts');
    const outDir = path.join(tempDir, 'generated');
    const pattern = `${contractsDir}/*.contract.ts`;

    writeContract(contractFile, 'demo.stale');
    expect(await runBridgekitCommand(generateArgs(pattern, outDir))).toBe(0);
    expect(existsSync(path.join(outDir, 'DemoStaleContract.kt'))).toBe(true);

    writeFileSync(contractFile, 'export const helper = 42;\n', 'utf8');

    expect(await runBridgekitCommand(generateArgs(pattern, outDir, true))).toBe(1);
    expect(stderrSpy.mock.calls.flat().join('')).toContain(
      'matched contract files exported zero BridgeContract tokens',
    );
  });

  test('accepts multi-file discovery when at least one matched file exports a contract', async () => {
    const contractsDir = path.join(tempDir, 'contracts');
    const outDir = path.join(tempDir, 'generated');
    const pattern = `${contractsDir}/*.contract.ts`;

    writeContract(path.join(contractsDir, 'demo.contract.ts'), 'demo.current');
    writeFileSync(path.join(contractsDir, 'helpers.contract.ts'), 'export const helper = 42;\n');

    expect(await runBridgekitCommand(generateArgs(pattern, outDir))).toBe(0);
    expect(await runBridgekitCommand(generateArgs(pattern, outDir, true))).toBe(0);
  });

  test('reports BridgeKit-marked generated files absent from the previous lock', async () => {
    const contractsDir = path.join(tempDir, 'contracts');
    const contractFile = path.join(contractsDir, 'demo.contract.ts');
    const outDir = path.join(tempDir, 'generated');
    const pattern = `${contractsDir}/*.contract.ts`;

    writeContract(contractFile, 'demo.current');
    expect(await runBridgekitCommand(generateArgs(pattern, outDir))).toBe(0);

    const unexpectedFile = path.join(outDir, 'UnexpectedContract.kt');
    writeFileSync(
      unexpectedFile,
      '// Generated by bridgekit 0.0.1-beta.0 — DO NOT EDIT.\nclass UnexpectedContract\n',
      'utf8',
    );

    expect(await runBridgekitCommand(generateArgs(pattern, outDir, true))).toBe(1);
    const stderr = stderrSpy.mock.calls.flat().join('');
    expect(stderr).toContain('UnexpectedContract.kt');
    expect(stderr).toContain('extra generated file');
    expect(existsSync(unexpectedFile)).toBe(true);
  });
});
